theme: minima
title: Your awesome title 
author: jevan4 
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  What are things I do during quarentine? I love drawing, I play piano, and I really like to code too! 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
